### ISSUE TITLE
Copy core to own file to prevent address collision issues in Linux

### ISSUE THREAD

**Issue by ctrlaltf2** [ctrlaltf2/lets-play#34]
Parallel universes happen if you load the same core twice.

**Comment by modeco80** [comment]
Would it be a good idea to do something like `<CoreSOName>.<emuID>` (Since the server itself won't let any other emulators with the same ID as another one exist, this should prevent any collision whilst being primitive)? Also, would it be wise to, upon server or emulator shutdown, delete copies of cores (I doubt having a bunch of the same small SO would be too bad, but I figure it's better to be clean than dirty)
